version: '3.9'
services:
  # Apache webserver service
  webserver:
    container_name: PHP-webServer
    image: ijazahmad/apache-php:v1
    ports:
      - 8000:80  
    depends_on:
      - postgres

  postgres:
    image: ijazahmad/postgres16:v1
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
  keycloak:
      image: ijazahmad/keycloak:v1 
      container_name: keycloak
      command: start-dev
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: test_database
        DB_USER: db_user
        DB_PASSWORD: db_password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        PROXY_ADDRESS_FORWARDING: "true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
